# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - name: Build
      run: npm run build
    - name: Upload to s3
      run: node ./scripts/publishS3.js upload
      env:
        CI: true
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
